# Generated by Django 3.1.7 on 2021-08-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210806_1137'),
        ('carts', '0002_auto_20210804_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='varitaion_values',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
